<h2>Timothy Fraser, PhD</h2>
<ul>
  <li><b>Researcher and Data Scientist</b></li>
  <li><b>Ezra Systems Postdoctoral Associate</b>, Systems Engineering Program, Cornell University</li>
  <li>Email: timothy.fraser.1@gmail.com | Address: 633 Rhodes Hall, 136 Hoy Road, Ithaca, NY 14850</li>
</ul>
<hr>
<table>
  <caption><b>Table of Contents</b></caption>
  <tr>
    <th><b>Type</b></th>
    <th colspan="5"><b>Section</b> (<i>Click to Jump to Sections!</i>)</th>
  </tr>
  <tr>
    <td><b>Sites</b></td>
    <td><a href="https://www.timothyfraser.com/">My Website</a></td>
    <td><a href="https://www.researchgate.net/profile/Timothy_Fraser2">ResearchGate</a></td>
    <td><a href="https://github.com/timothyfraser/">Github</a> </td>
    <td><a href="https://dataverse.harvard.edu/dataverse/timothyfraser/">Dataverse</a> </td>
    <td><a href="https://twitter.com/Timothy_Fraser1">Twitter</a></td>
  </tr>
    <td><b>Background</td>
    <td><a href="#current">Positions</a></td>
    <td><a href="#education">Education & Skills</a></td>
    <td><a href="#publications">Publications</a></td>
    <td><a href="#funding">Funding & Grants</a></td>
    <td><a href="#awards">Awards</a></td>
  <tr>
    <td><b>Teaching & Mentoring</b></td>
    <td><a href="#teaching">Teaching</a></td>
    <td><a href="#mentoring">Student Research & Mentoring</a></td>
    <td><a href="#service">Academic Service</a></td>
    <td><a href="#outreach">Community Outreach</a></td>
    <td><a href="#language">Japanese</a></td>
  </tr>
  <tr>
    <td><b>Statements</b></td>
    <td colspan="2"><a href="https://github.com/timothyfraser/cv/files/7790815/Fraser_research_statement.pdf"><b>Download Research Statement</b></a></td>
    <td colspan="3"><a href="https://github.com/timothyfraser/cv/files/7790816/Fraser_teaching_portfolio.pdf"><b>Download Teaching Portfolio</b></a></td>
  </tr>
</table>

<br>
<br>
<hr> 

<h3><a id="current">Positions</a></h3>

<table>
  <tr>
    <th>Years</th>
    <th>Position</th>
    <th>Description</th>
    <th>Type</th>
  </tr>
  
  <tr>
    <td>2022-Present</td>
    <td><b>Ezra Systems Postdoctoral Associate</b></td>
    <td>Cornell University, Systems Engineering Program</td>
    <td>Research</td>
  </tr>
  
  <tr>
    <td>2022-Present</td>
    <td><b>Instructor</b>
    <td>Cornell University, Systems Engineering Program, statistics-related courses</td>
    <td>Teaching</td>
  <tr>
    <td>2022-Present</td>
    <td><b>Grant Coordinator</b></td>
    <td>Cornell University, Center for Transportation, Environment, and Community Health (CTECH)</td>
    <td>Admin</td>
  </tr>
  
  <tr>
    <td>2021-2023</td>
    <td><b>Data Consultant</b></td>
    <td>NGO Resilient Cloverdale<br>Social network analysis and survey weighting analyses for evaluating community resilience in California.</td>
    <td>Consulting</td>
  </tr>

  <tr>
    <td>2019-2022</td>
    <td><b>Data Analyst</b></td>
    <td>NSF Grant Project, Northeastern University Sociology Dept.<br>"Diffusion of Ideas of Gender Equity Interventions Through Networks of U.S. Universities".<br>Applied Data science and Network Analysis, led by Dr. Kathrin Zippel and Dr. Laura Nelson (9 months)</td>
    <td>Research</td>
  </tr>

  <tr>
    <td>2019-2021</td>
    <td><b>Data Analyst</b></td>
    <td>Grant Project, Northeastern University Political Science Dept.<br>"Impacts of Partisan Polarization and Voting Preferences on the Public’s Health".<br>Data science and survey design research for 2 national surveys for Northeastern University-funded project, led by Dr. Daniel Kim, Dr. Costas Panagopoulos,  Dr. Daniel Aldrich (8 months).</td>
    <td>Research</td>
  </tr>

  <tr>
    <td>2021</td>
    <td>Data Analyst</td>
    <td>Book Project, Northeastern University Political Science Dept.<br>"Congressional Challengers: Candidate Quality in US Elections to Congress".<br>Modeling and Visualization for book project for Dr. Costas Panagopoulos.</td>
    <td>Research</td>
  </tr>

  <tr>
    <td>2020</td>
    <td>Data Analyst</td>
    <td>Book Project, Northeastern University Political Science Dept.<br>"Bases Loaded: How US Presidential Campaigns Are Changing and Why It Matters". Modeling and Visualization for book project for Dr. Costas Panagopoulos.</td>
    <td>Research</td>
  </tr>

  <tr>
     <td>2020</td>
     <td>Data Consultant</td>
     <td><b>United Nations Development Program Mexico Accelerator Lab</b>: Designed survey methodology for field experiment on measuring and building social capital in Mexico City neighborhoods.</td>
     <td>Consulting</td>
  </tr>

  <tr>
     <td>2020</td>
     <td>Data Consultant</td>
     <td><b>United Nations Development Program Paraguay Accelerator Lab</b>: Generated methodology for mapping social capital and social vulnerability in Paraguay, using spatial analysis techniques to account for data availability limitations.</td>
     <td>Consulting</td>
  </tr>

  <tr>
     <td>2020-2022</td>
     <td>Instructor</td>
     <td>Northeastern University Political Science Department</td>
     <td>Teaching</td>
  </tr>

  <tr>
     <td>2017-2019</td>
     <td>Teaching Assistant</td>
     <td>Northeastern University Political Science Department</td>
     <td>Teaching</td>
  </tr>
</table>


<br>
<br>
<hr>

<h3> <a id="skills">Education & Skills</a></h3>

<ul>
  <li>**Ph.D. Political Science**	(*Public Policy and Comparative Politics*) 
  <br>Northeastern University, Boston, 2017-2022
    </li>
  <li>
  **M.A. Political Science**	(*Public Policy*)
  <br>Northeastern University, Boston, 2017-2019
  </li>
  <li> **Fulbright Fellowship** (Geography)
<br>Kyushu University, Japan, 2016-2017
  </li>
  <li>**B.A. International & Global Studies** (*East Asian Studies, summa cum laude*)	
<br>Middlebury College, Vermont, 2012-2016
  </li>
</ul>
    
**Skills**: **Expert in R** | **Data Visualization and Design** | **Mixed Methods** | **GIS, Social Network Analysis, & Big Data**
- R, RMarkdown, ShinyApps, Dashboards, HTML, CSS, MariaDB, MySQL, SQLite, Network Analysis, ERGMs, GIS, ArcGIS, SPSS, Tableau, `ggplot2`
- **Expertise:** Community Resilience, Disasters, Evacuation, Health, Environment, Renewable Energy, US, Japan, Cities

---

<br>
<br>



### Preprints
- **Timothy Fraser**. [Where the Grass Is Greener: Social Infrastructure and Resilience to COVID-19.](http://dx.doi.org/10.2139/ssrn.3841826)
- **Timothy Fraser**, Katherine Van Woert, Sophia Olivieri, Jonathan Baron, Katelyn Buckley, & Pamela Lalli. [Cycling Cities: Measuring Transportation Equity in Bikeshare Networks](https://dx.doi.org/10.2139/ssrn.4076776).

### Reports (2)
- Daniel Aldrich, Courtney Page-Tan, **Timothy Fraser**, & Takahiro Yabe. (2022). Social Capital, Mobility, and Evacuation Destinations During the Marshall Fire. [Natural Hazards Center Quick Response Grant Report Series](https://hazards.colorado.edu/quick-response-report/social-capital-mobility-and-evacuation-destinations-during-the-marshall-fire), 348. Boulder, CO: Natural Hazards Center, University of Colorado Boulder.
- Daniel Aldrich, **Timothy Fraser**, Juheon Lee, Courtney Page-Tan, & Toshiaki Yoshida. (2020). Social Ties, Quarantine Policy, and the Spread of COVID-19. [Natural Hazards Center Quick Response Grant Report Series](https://hazards.colorado.edu/quick-response-report/social-ties-quarantine-policy-and-the-spread-of-covid-19), 314. Boulder, CO: Natural Hazards Center, University of Colorado Boulder.

### Chapters in Edited Volumes (7)
- **Timothy Fraser** (2023). It's Who You Know: How social networks help cities rebuild with renewables after disaster. In Paola Cavaliere, ed. Handbook of Disaster Studies in Japan. Amsterdam University Press/MHM Limited. (forthcoming)
- **Timothy Fraser** (2023). Stronger Together: The Critical Role of Bridging and Linking Social Capital in Evacuation Outcomes. In Paola Cavaliere, ed. Handbook of Disaster Studies in Japan. Amsterdam University Press/MHM Limited. (forthcoming)
- **Timothy Fraser**, Courtney Page-Tan, & Daniel P. Aldrich. (2021). [Social Network Analysis for Disasters.](https://www.researchgate.net/publication/351283811_Social_Network_Analysis_for_Disaster_Management_Research) In Jason Rivera, ed. Research Methods of Disaster and Emergency Management: Social Science Approaches in Application.
- Courtney Page-Tan, **Timothy Fraser**, & Daniel P. Aldrich. (2021). [Mapping Resilience: GIS Techniques for Disaster Studies.](https://www.researchgate.net/publication/351283898_Mapping_Resilience_GIS_Techniques_for_Disaster_Studies) In Jason Rivera, ed. Research Methods of Disaster and Emergency Management: Social Science Approaches in Application.
- **Timothy Fraser** & Andrew J. Chapman. (2020). [Social Sustainability in Cities: Urban Energy.](https://www.researchgate.net/publication/344196674_Sustainability_of_Urban_Energy?_sg=ozKKOM4138T2xnoefuxus60AbYJzy10JR1-5uCDKGB-7PdNexeoPKIssPqP7FMiCDY87UgqDEadMeuloLnlOlfXs3V0eDLWP2LG8w7kh.lRCg37Dj8FDrfz9qlZx1WNllujoXNvuot1BfMTXBw0qKAjQxo2PIMTLjUKdw0UcPyxU0TbAcgmrZSKsCwNQqfA) In Alvarez-Risco, A., Rosen, M., Del-Aguila-Arcentales, S, & Marinova, D. Building sustainable cities: Social, Economic and Environmental Factors, Springer-Nature.
- **Timothy Fraser** and Daniel P. Aldrich. (2019). [East Asia's Nuclear Policies: Fukushima Effect or a Nuclear Renaissance?](https://issuu.com/georgetownsfs/docs/gjaa_vol.4_no.2/65) Georgetown Journal of Asian Affairs. 
- Daniel P. Aldrich, Courtney Page-Tan, and **Timothy Fraser**. (2018). [A Janus Faced Resource: Social Capital and Resilience Trade-offs.](https://irgc.epfl.ch/wp-content/uploads/2018/11/Aldrich-et-al-for-IRGC-Resilience-Guide-Vol-2-2018.pdf) International Risk Governance Council Resource Guide, vol 2.

### Under Review

- Big Spenders: Large-N Measures of Urban Regimes in Japanese Cities.
- Where the Grass Is Greener: Social Infrastructure and Resilience to COVID-19
- How Far I'll go: Distance and Access to Social Infrastructure to Urban Neighborhoods. (with Olivia Feeley, Andres Ridge, Ava Cervini, Vincent Rago, Kelly Gilmore, & Gianna Worthington)
- Networked Neighborhoods: The role of Social Infrastructure in Social Connectivity in Urban Systems (with Khushi Patel)
- Cycling Cities: Measuring Transportation Equity in Bikeshare Networks (with Katherine Van Woert, Sophia Olivieri, Jonathan Baron, Katelyn Buckley, Pamela Lalli)

### Working Papers

- Japan’s Green Voters: The Role of Social Capital in Women’s Movements against Nuclear Power Policy
- Boomtown or Bust? Policy Feedback Effects of Controversial Facilities on Social Capital in Japan (with Toshiaki Yoshida)
- Bottom-up or Top-Down? Bridging Academics in the ADVANCE Network for Gender Equity (with Laura K. Nelson and Kathrin Zippel)
- Networks of Solar Cities.

---

### Invited Talks (10+)

- Won't You be My Neighbor? Mapping Social Infrastructure and Social Capital across North America with Big Data. Guest lecture presented for Course "Industrial Big Data Analytics and Machine Learning", Systems Engineering Program, Cornell Unviersity. April 19, 2023.
- Leapfrogging or Lagging? Drivers of social equity from renewable energy transitions globally. Guest lecture presented for Course "Quantitative Techniques", Political Science Department, Cornell University. March 20, 2023.
- Where the Grass Is Greener: Social Infrastructure and Resilience to COVID-19. Presented for UTokyo Center for Contemporary Japanese Studies [Virtual]. June 7, 2022.
- Fleeing the Unsustainable City: Social Capital’s Role in Hurricane Evacuation. Presented for Department of Environmental Science & Policy, George Mason University. March 18, 2022.
- Mapping Social Infrastructure: Validating API Measures. Presented for the Northeastern University Lab for Text, Maps, and Networks, February 16, 2022.
- Mapping Urban Policy: Social Infrastructure in US Cities. Presented for the Dept. of Urban Studies at Worcester State University, January 26, 2022.
- Power to the People: The Value of Urban Regimes and Social Capital in Building Solar Cities. Presented for the International Institute of Carbon Neutral Energy Research, Kyushu University, October 27, 2021.
- Mapping Social Infrastructure for Disaster and Pandemic Resilience: A Case Study of Boston. Presented for the Dept. of American Studies at Indiana University–Purdue University Indianapolis, June 3, 2021.
- Who Governs in Fukushima’s Wastewater Problem? Lessons from Nuclear Power Plant Restarts. Presented for the Nuclear Fusion Project, May 17, 2021.
- Restarting the Sendai Reactor: Japanese Civic Activism after Fukushima. Presented at Middlebury College Rohatyn Center for Global Affairs, February 24, 2017.
- Public Opinion Survey Design and Weighting. Presented for the Stanton Foundation, September 2021.

### Conference Talks (8+)

- Cycling Cities: Measuring Transportation Equity in Bikeshare Networks. Presented for Political Networks Annual Conference 2022 (PolNet), June 22, 2022.
- Opportunists and Organizers: The Value of Urban Regimes and Social Capital in Building Solar Cities. Presented for Midwestern Political Science Association Annual Conference, April 9, 2022.
- Getting to Know You: Mapping Social Infrastructure in American Neighborhoods for Community Resilience. Presented for Midwestern Political Science Association Annual Conference, April 8, 2022.
- In Friends We Trust: Soft Policy and the Janus-Faced Nature of Social Capital in Evacuation Networks. Presented for American Political Science Association Annual Conference, October 3, 2021.
- Bottom-up or Top-Down? Bridging Academics in the ADVANCE Network for Gender Equity (with Laura K. Nelson and Kathrin Zippel). Presented for American Sociological Association Annual Conference, August 9, 2021.
- Japan’s Green Voters: The Role of Social Capital in Women’s Movements against Nuclear Power Policy. Presented for the Asian Online Political Science Seminar Series, May 12, 2021.
- Do All Roads Lead to Sapporo: A Social Network Analysis of Evacuation. Presented at New England Political Science Association Conference, Portland, ME, April 24, 2019.
- Youth Politics in Japan after 3.11: Political Geographies of Tokyo and Tohoku. Presented at Bard College Sustainability in Asia Conference, April 17, 2015.

### Public Scholarship & Press (4)
- Reviewed by: Carlos Irwin Oronce and Yusuke Tsugawa. [Bonding and linking social capital are key determinants for successful pandemic policy.](https://doi.org/10.1016/j.socscimed.2021.114376) Social Science & Medicine 287, 114376.
- Quoted in: Marcos Cabello. [Rumors during a natural disaster may facilitate greater evacuation — even when unnecessary.](https://academictimes.com/rumors-during-a-natural-disaster-may-facilitate-greater-evacuation-even-when-unnecessary/) The Academic Times, June 8, 2021.
- Quoted in: Sophie Yeo. [When Climate Disaster Strikes, It's Renewable Energy That Keeps The Lights On.](https://www.huffingtonpost.co.uk/entry/renewables-clean-energy-climate-disasters_n_5fad67d1c5b6cae94043c56b) Huffington Post, December 1, 2020. 
- Timothy Fraser and Daniel P. Aldrich. [The Fukushima Effect at Home: New roles for local actors in Japan's energy policy.](https://www.advancedsciencenews.com/the-fukushima-effect-at-home-new-roles-for-local-actors-in-japans-energy-policy/) Advanced Science News. June 9, 2020

#### R Packages for Public Data Science

- `simulate`. (2022). Package for tidyverse friendly statistical simulation! [Hosted on Github](https://github.com/timothyfraser/simulate).
- `tidyfault`. (2022). Package for tidy fault tree analysis! [Hosted on Github](https://github.com/timothyfraser/tidyfault)

#### Dashboards for Public Data Communication & Visualization (4)
- [Mapping Social Infrastructure in Boston](https://timfraser.shinyapps.io/boston_social_infra/)
- [Community Resilience in Japan](https://timfraser.shinyapps.io/community_resilience_in_japan)
- [Measuring Environmental Racism in US Counties](https://timfraser.shinyapps.io/environmental_racism)
- [Testing the Fukushima Effect on Japanese Elections with Inferential Statistics](https://timfraser.shinyapps.io/lesson_5_inferential_stats/)

---

<br>
<br>

## <a id="funding">Research Funding & Grants</a>

- 2022: Natural Hazards Center Quick Response Grant. Drivers of evacuation: A multi-level study of social capital and mobility during Covid-19. Natural Hazards Center Quick Response Program. Co-Principal Investigator. Credit: $5,000
- 2021: NULab for Texts, Maps, and Networks Seedling Grant. [Mapping Social Infrastructure for Disaster and Pandemic Resilience](https://cssh.northeastern.edu/nulab/mapping-social-infrastructure-disaster-resilience/). Northeastern University. Co-Principal Investigator. Credit: $3,000
- 2020: Fulbright Graduate Fellowship. Credit: Full Year Fellowship.	(declined due to pandemic)
- 2020: Japan Foundation Doctoral Fellowship. Credit: Full Year Fellowship.  (declined due to pandemic)
- 2020: Social Science Research Council’s Nomination for Japan Society for Promotion of Science Fellowship. Credit: Full Year Fellowship.  (declined due to pandemic)
- 2020: Natural Hazards Center Quick Response Grant. CONVERGE Covid -19 Working Group for Social Ties, Mobility, and Covid-19 Spread Rates. Natural Hazards Center Quick Response Program. Collaborator. Credit: $5,000
- 2018: Northeastern University Asian Studies Research Award. Credit: $2000
- 2016: Fulbright Study/Research Fellowship in Japan. Credit: $20,000.
- 2015: Middlebury College Rohatyn Center Grant for Summer Research. Credit: $5000
- 2015: Middlebury College Cross-Cultural Community Engagement Grant. Credit: $1000
- 2014: Middlebury College Mellon Grant for Study Abroad Research. Credit: $2500

## <a id="awards">Awards</a>

<br>
<br>

## <a id="service">Academic Service</a>

### Reviewer for 30 journals:
  - 11 journals on **Energy & Environment**: *Energy Research & Social Science, Applied Energy, Cleaner Production Letters, Environmental Politics, Journal of Environmental Management, Utilities Policy, Environmental Sociology, Ecology & Society, Sustainability Science, Frontiers In Sustainable Cities, Energies (MDPI).* 
  - 5 journals on **Urban Systems**: *Socio-Economic Planning Sciences, International Journal of Project Management, Journal of Management in Engineering, Sustainability (MDPI), Journal of Marine Science and Engineering (MDPI).*
  - 6 journals on **Disasters & Health**: *Nature: Scientific Reports, PLOS ONE, Social Science & Medicine, International Journal of Disaster Risk Reduction, International Journal of Disaster Risk Science, Disasters.*
  - 8 journals on **Political Science**: *Politics and Life Sciences, Social Science Research, Journal of Public and Nonprofit Affairs, Politics and Governance, European Policy Analysis, Social Science Japan Journal, Oxford University Press, Social Sciences (MDPI)*

### Conference Roles
- Chair and Discussant for: Midwestern Political Science Association 2022 Conference Panel: *Political Networks in Comparative Politics.*
- Chair and Discussant for: Midwestern Political Science Association 2022 Conference Panel: *Impacts of Climate Change: New Directions.*
- Discussant for: American Political Science Association 2021 Conference Panel: *From Framing to Shaming: Generating Support for Environmental Policy.*
- Methods Tutorials for [Environmental Social Science in R](https://www.timothyfraser.com/tutorials-in-r)
- Lead organizer for conference: Power and Protest: Global Responses to Atomic Energy, Middlebury College Rohatyn Center for Global Affairs. January 21-22, 2016.

---

## <a id="teaching">Teaching</a>

- **2022-present: Instructor, Cornell University**
  - Systems Reliability & Six Sigma (Fall 2022)
  - Systems Architecture (Spring 2023)

- **2020-2021: Instructor of Record, Northeastern University Political Science**
  - Quantitative Techniques & Statistics in R (Fall 2021, Spring 2020)
  - Research Methods in Political Science (Summer 2021)
  - Masters Capstone Coordinator (Fall 2021, Spring 2021, Spring 2020)

- **2021: Methods Tutorials for Quantitative Social Science in R** (22)
  - See my online tutorials on [RPubs](https://rpubs.com/timothyfraser)! 
    - [Statistical Simulation and Food Deserts](https://rpubs.com/timothyfraser/statistical_simulation_food_deserts)
    - [Multiple Regression and Disaster Effects](https://rpubs.com/timothyfraser/multiple_regression)
    - [Mapping Raster Data](https://rpubs.com/timothyfraser/mapping_raster_data_in_the_tidyverse)

- **2017-2019: Graduate Teaching Assistant, Northeastern University Political Science**
  - Introduction to Comparative Politics with Dr. Ioannis Livanis, Dr. Colin Brown (2 times)
  - Introduction to American Government and Politics with Dr. Michael Tolley (2 times)
  - Quantitative Techniques & Statistics with Dr. Colin Brown
  - Disasters and Recovery Summer Course in Japan with Dr. Daniel Aldrich
  - American Political Thought with Dr. William Mayer
  - Sexuality, Gender, and the Law with Dr. Libby Adler

---

<br>
<br>

## <a id="mentoring">Mentoring & Research with Students</a> (21 undergrads and 10 masters students)
(Students' names marked in **bold**!)

### 2020-2022: **Environmental Politics and Computational Social Science Working Group**

- Timothy Fraser, **Olivia Feeley, Andres Ridge, Ava Cervini, Vincent Rago, Kelly Gilmore, Gianna Worthington.** (2022). How Far I'll go: Distance and Access to Social Infrastructure to Urban Neighborhoods. (Under Review)
  - Presented for the College of Social Sciences & Humanities Undergraduate Research Forum at Northeastern University, March 23, 2022.
- Timothy Fraser, **Katherine Van Woert, Sophia Olivieri, Pamela Lalli, Katelyn Buckley, Jonathan Baron.** (2022) Cycling Cities: Measuring Transportation Equity in Bikeshare Networks. (Under Review)
  - Presented for the College of Social Sciences & Humanities Undergraduate Research Forum at Northeastern University, March 24, 2022.
  - Presented for the Research, Innovation, Scholarship and Entrepreneurial Expo (RISE) at Northeastern University, April 2022. [See my students' talk here!](https://youtu.be/es1jtFSZVxk)
- Timothy Fraser and **Khushi Patel**. Networked Neighborhoods: The role of Social Infrastructure in Social Connectivity in Urban Systems. (Working Paper).
  - Presented for the Research, Innovation, Scholarship and Entrepreneurial Expo (RISE) at Northeastern University, April 2022. [See my student's talk here!](https://youtu.be/6zYmv_Bw7ak) 
- Timothy Fraser, **Mary Bancroft, Andrew Small,** & **Lily Cunningham.** (2022). Leaders or Networkers? The Role of Mayors in Renewable Energy Transition. Environmental Innovations & Societal Transitions. Accepted January 7, 2022.
- Timothy Fraser, and **Nikki Naquin.** (2022). Better Together? The role of Social Capital in Urban Social Vulnerability. Under Review.
  - Presented for the College of Social Sciences & Humanities Undergraduate Research Forum at Northeastern University, March 23, 2022.
- Timothy Fraser, and **Dustin Hinkley.** (2021). It takes a Village: How Representation on Environmental Advisory Committees shape Emissions in Tokyo Wards (Working Paper)
- Timothy Fraser, **Lily Cunningham**, & **Amos Nasongo**. (2021). Build back better? Effects of crisis on climate change adaptation in Japan and the US. Global Environmental Politics 21(1), 54-75.
- Timothy Fraser, **Lily Cunningham, Mary Bancroft, Amy Hunt, Eri Lee,** & **Amos Nasongo**. (2020). Climate Crisis at City Hall: How Japanese communities mobilize to eliminate emissions. Environmental Innovations and Societal Transitions. Accepted September 30, 2020.

### 2020-2021: **Disaster Evacuation in Japan**

- Timothy Fraser, **Larissa Morikawa,** and Daniel P. Aldrich (2021). Rumor has it: The role of social ties and misinformation in evacuation to nearby shelters after disaster. Climate Risk Management 33, 100320. [Open Access]
- Timothy Fraser, Daniel P. Aldrich, and **Larissa Morikawa.** (2021). Do All Roads Lead to Sapporo? The Role of Linking and Bridging Ties in Evacuation Decisions. Ecology & Society. Accepted December 7, 2021.

### 2019-2020: **Disaster Recovery Committee Projects**

- Timothy Fraser, Daniel P. Aldrich, **Andrew Small**, and Andrew Littlejohn. (2021). In the Hands of a Few: Disaster Recovery Committee Networks. Journal of Environmental Management 280, 111643.
- Timothy Fraser, Daniel P. Aldrich, and **Andrew Small**. (2021). Connecting Social Capital and Vulnerability: A Citation Network Analysis of Disaster Studies. Natural Hazards Review 22(3).
- Timothy Fraser, Daniel P. Aldrich, & **Andrew Small**. (2021). Seawalls or social recovery? The role of policy networks and design in disaster recovery. Global Environmental Change 70, 102342.

### 2020-2021: **Masters Capstone Advising for NU School of Public Policy and Urban Affairs**

- Uneven Paths: Recovery in Louisiana Parishes after Hurricanes Katrina and Rita (with students **Alex Poniatowski, Nicholas Hersey,  & Haoran Zheng**) (Published in *J. Environental Management*!)
- Disaster Recovery Committees in New York City after Hurricane Sandy (with students **Lucy Hewitt, Ziyue Chen, & Matthew Cherkerzian**)
- Mapping Social Infrastructure in Boston Neighborhoods (with students **Winta Tekle, Napuck Cherdchaiyapong, Joel Zayas, & Erin Thomas**) (Published in *Urban Climate*!)


## <a id="outreach">Community Outreach</a>

- 2023: Invited Panelist for **Cornell University Neurodiversity Week Event: Stories of Neurodiversity** (March 13, 2023).

- 2016-2017: **Susenji Elementary School Student Supporter in Fukuoka, Japan**
  - Tutored Japanese students in ESL and non-native students in math and Japanese language

- 2015-2016: **Language in Motion Program Support Assistant at Middlebury College**
  - Arranged intercultural education training and programming in local Vermont high schools in paid internship. Presented on Japanese culture and disaster studies and Turkish politics.

- 2015: **Community Engagement Intern at Middlebury College**
  - Networked with community and college organizations to facilitate service-learning opportunities on Vermont public education, health, and poverty in paid internship.

- 2015: **James Martin Center for Nonproliferation Studies**: Produced public-facing map of trafficking of nuclear materials and nuclear security policy quality. Studied nuclear security issues from experts in seminar-style classes. Paid intern.

- 2014: **Changemakers Talent Mapping Project, Ashoka Japan**: Researched potential of social campaigns on education, environment, healthcare, and economy. English-Japanese translation services for Changemakers Talent Mapping Project.


## <a id="japanese">Japanese Language Training</a>

10 years using and learning Japanese
  
- <b>Middlebury College</b> (<i>1st-2nd Year Japanese, 5th year Japanese, 2012-2016</i>)
  
- <b>Middlebury Summer Language Schools</b> (<i>3rd Year Japanese, Summer 2014</i>)

- <b>International Christian University, Tokyo</b> (<i>4th Year Japanese,	Fall 2014</i>)
  
- <b>Private Tutoring, Fukuoka</b> (<i>Advanced Japanese, Fulbright Thesis in Japanese, 2016-2017</i>)
  
- <b>Private Tutoring, Boston</b> (<i>Advanced Japanese, Communicating Research in Japanese, 2021</i>)

